export const staffInicial = [
  {
    id: 1,
    firstName: "Hernán",
    lastName: "Knee",
    titulo: "Dr.",
    matricula: "45713",
    especialidad: 1, // ID de especialidad
    descripcion: "Especialista en Clínica Médica con amplia experiencia en atención primaria.",
    obraSocial: [1, 2, 3, 4], // Array de IDs de obras sociales
    valorConsulta: 5000,
    telefono: "(011) 1234-5678",
    email: "hknee@clinicaidw.com"
  },
  {
    id: 2,
    firstName: "Martina",
    lastName: "Liguori",
    titulo: "Dra.",
    matricula: "57143",
    especialidad: 1,
    descripcion: "Profesional dedicada a la Clínica Médica, enfocada en la salud preventiva.",
    obraSocial: [1, 5, 6, 7, 8],
    valorConsulta: 5500,
    telefono: "(011) 2345-6789",
    email: "mliguori@clinicaidw.com"
  },
  {
    id: 3,
    firstName: "Luis",
    lastName: "Pérez",
    titulo: "Dr.",
    matricula: "11773",
    especialidad: 2,
    descripcion: "Cardiólogo experto en diagnóstico y tratamiento de enfermedades cardíacas.",
    obraSocial: [2, 6, 3, 9, 10, 15],
    valorConsulta: 7000,
    telefono: "(011) 3456-7890",
    email: "lperez@clinicaidw.com"
  },
  {
    id: 4,
    firstName: "Hortensia",
    lastName: "Otero",
    titulo: "Dra.",
    matricula: "34704",
    especialidad: 2,
    descripcion: "Especialista en Cardiología con enfoque en pacientes geriátricos.",
    obraSocial: [9, 5, 11, 9, 8],
    valorConsulta: 7200,
    telefono: "(011) 4567-8901",
    email: "hotero@clinicaidw.com"
  },
  {
    id: 5,
    firstName: "Héctor Ignacio",
    lastName: "Bolívar",
    titulo: "Dr.",
    matricula: "50850",
    especialidad: 3,
    descripcion: "Ginecólogo con especialización en obstetricia y salud reproductiva.",
    obraSocial: [1, 13, 14],
    valorConsulta: 6500,
    telefono: "(011) 5678-9012",
    email: "hbolivar@clinicaidw.com"
  },
  {
    id: 6,
    firstName: "Julia",
    lastName: "Sánchez",
    titulo: "Dra.",
    matricula: "12936",
    especialidad: 3,
    descripcion: "Profesional en Ginecología dedicada a la atención integral de la mujer.",
    obraSocial: [9, 1, 6, 9, 8, 4],
    valorConsulta: 6800,
    telefono: "(011) 6789-0123",
    email: "jsanchez@clinicaidw.com"
  },
  {
    id: 7,
    firstName: "Marcela",
    lastName: "Piatti",
    titulo: "Dra.",
    matricula: "77354",
    especialidad: 4,
    descripcion: "Traumatóloga especializada en lesiones deportivas y ortopedia.",
    obraSocial: [6, 11, 12, 8, 4],
    valorConsulta: 6000,
    telefono: "(011) 7890-1234",
    email: "mpiatti@clinicaidw.com"
  },
  {
    id: 8,
    firstName: "Luisina",
    lastName: "Porta",
    titulo: "Dra.",
    matricula: "08364",
    especialidad: 4,
    descripcion: "Especialista en Traumatología con experiencia en cirugía reconstructiva.",
    obraSocial: [1, 5, 13, 12, 15],
    valorConsulta: 6200,
    telefono: "(011) 8901-2345",
    email: "lporta@clinicaidw.com"
  },
  {
    id: 9,
    firstName: "Cristóbal",
    lastName: "Camacho",
    titulo: "Dr.",
    matricula: "63861",
    especialidad: 5,
    descripcion: "Pediatra comprometido con la salud infantil y el desarrollo temprano.",
    obraSocial: [9, 10, 11, 12],
    valorConsulta: 5800,
    telefono: "(011) 9012-3456",
    email: "ccamacho@clinicaidw.com"
  },
  {
    id: 10,
    firstName: "Ernestina",
    lastName: "Martínez",
    titulo: "Dra.",
    matricula: "55048",
    especialidad: 5,
    descripcion: "Especialista en Pediatría con enfoque en nutrición y crecimiento.",
    obraSocial: [9, 6, 3, 4, 15],
    valorConsulta: 5900,
    telefono: "(011) 0123-4567",
    email: "emartinez@clinicaidw.com"
  }
];
